use std::path::Path;

use image::ImageFormat;
use objc2::{rc::autoreleasepool, runtime::ProtocolObject};
use objc2_app_kit::{
    NSPasteboard, NSPasteboardItem, NSPasteboardTypeFileURL, NSPasteboardTypeHTML,
    NSPasteboardTypePNG, NSPasteboardTypeRTF, NSPasteboardTypeString, NSPasteboardTypeTIFF,
    NSPasteboardWriting,
};
use objc2_foundation::{NSArray, NSData, NSString, NSURL};
use sha2::{Digest, Sha256};

use crate::{
    error::AppError,
    models::{CapturedClipboard, ClipboardItemDetail, ClipboardKind},
    native_macos::FrontmostApp,
};

const TEXT_LIMIT: usize = 2 * 1024 * 1024;
const IMAGE_LIMIT: usize = 25 * 1024 * 1024;
const FILE_LIMIT: usize = 100;
const SENSITIVE_TYPES: [&str; 3] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

#[derive(Clone, Debug)]
pub struct WriteReceipt {
    pub change_count: i64,
    pub content_hash: String,
}

pub fn change_count() -> i64 {
    autoreleasepool(|_| NSPasteboard::generalPasteboard().changeCount() as i64)
}

pub fn read_capture(source: FrontmostApp) -> Result<Option<CapturedClipboard>, AppError> {
    autoreleasepool(|_| {
        let pasteboard = NSPasteboard::generalPasteboard();
        let file_url_type = unsafe { NSPasteboardTypeFileURL };
        let png_type = unsafe { NSPasteboardTypePNG };
        let tiff_type = unsafe { NSPasteboardTypeTIFF };
        let jpeg_type = NSString::from_str("public.jpeg");
        let string_type = unsafe { NSPasteboardTypeString };
        let html_type = unsafe { NSPasteboardTypeHTML };
        let rtf_type = unsafe { NSPasteboardTypeRTF };
        let Some(items) = pasteboard.pasteboardItems() else {
            return Ok(None);
        };

        for item in items.iter() {
            for data_type in item.types().iter() {
                if SENSITIVE_TYPES.contains(&data_type.to_string().as_str()) {
                    return Ok(None);
                }
            }
        }

        let files: Vec<String> = items
            .iter()
            .filter_map(|item| item.stringForType(file_url_type))
            .filter_map(|value| NSURL::URLWithString(&value))
            .filter_map(|url| url.path())
            .map(|path| path.to_string())
            .collect();
        if !files.is_empty() {
            if files.len() > FILE_LIMIT {
                return Err(AppError::ContentTooLarge);
            }
            let mut hasher = Sha256::new();
            hasher.update(b"files\0");
            for file in &files {
                hasher.update(file.as_bytes());
                hasher.update(b"\0");
            }
            let title = file_title(&files);
            let byte_size = files
                .iter()
                .filter_map(|file| std::fs::metadata(file).ok())
                .map(|metadata| metadata.len())
                .sum();
            return Ok(Some(CapturedClipboard {
                kind: ClipboardKind::Files,
                title,
                content: String::new(),
                html: None,
                rtf: None,
                image_png: None,
                files,
                source_name: source.name,
                source_bundle_id: source.bundle_id,
                byte_size,
                hash: hex::encode(hasher.finalize()),
            }));
        }

        let image_data = pasteboard
            .dataForType(png_type)
            .or_else(|| pasteboard.dataForType(&jpeg_type))
            .or_else(|| pasteboard.dataForType(tiff_type));
        if let Some(data) = image_data {
            let bytes = data.to_vec();
            if bytes.len() > IMAGE_LIMIT {
                return Err(AppError::ContentTooLarge);
            }
            let decoded =
                image::load_from_memory(&bytes).map_err(|_| AppError::ClipboardUnavailable)?;
            let dimensions = (decoded.width(), decoded.height());
            let mut writer = std::io::Cursor::new(Vec::new());
            decoded
                .write_to(&mut writer, ImageFormat::Png)
                .map_err(|_| AppError::ClipboardUnavailable)?;
            let png = writer.into_inner();
            if png.len() > IMAGE_LIMIT {
                return Err(AppError::ContentTooLarge);
            }
            let hash = hash_bytes(b"image\0", &png);
            return Ok(Some(CapturedClipboard {
                kind: ClipboardKind::Image,
                title: format!("图片 · {} × {}", dimensions.0, dimensions.1),
                content: String::new(),
                html: None,
                rtf: None,
                image_png: Some(png.clone()),
                files: vec![],
                source_name: source.name,
                source_bundle_id: source.bundle_id,
                byte_size: png.len() as u64,
                hash,
            }));
        }

        let Some(text) = pasteboard.stringForType(string_type) else {
            return Ok(None);
        };
        let text = text.to_string();
        if text.len() > TEXT_LIMIT {
            return Err(AppError::ContentTooLarge);
        }
        let html = pasteboard
            .dataForType(html_type)
            .map(|value| value.to_vec());
        let rtf = pasteboard.dataForType(rtf_type).map(|value| value.to_vec());
        let title = text_title(&text);
        let hash = hash_bytes(b"text\0", text.as_bytes());
        Ok(Some(CapturedClipboard {
            kind: ClipboardKind::Text,
            title,
            content: text.clone(),
            html,
            rtf,
            image_png: None,
            files: vec![],
            source_name: source.name,
            source_bundle_id: source.bundle_id,
            byte_size: text.len() as u64,
            hash,
        }))
    })
}

pub fn write_item(
    item: &ClipboardItemDetail,
    image_png: Option<&[u8]>,
    html: Option<&[u8]>,
    rtf: Option<&[u8]>,
) -> Result<WriteReceipt, AppError> {
    autoreleasepool(|_| {
        let pasteboard = NSPasteboard::generalPasteboard();
        let file_url_type = unsafe { NSPasteboardTypeFileURL };
        let png_type = unsafe { NSPasteboardTypePNG };
        let string_type = unsafe { NSPasteboardTypeString };
        let html_type = unsafe { NSPasteboardTypeHTML };
        let rtf_type = unsafe { NSPasteboardTypeRTF };
        pasteboard.clearContents();
        let mut objects = Vec::new();
        let hash = match item.summary.kind {
            ClipboardKind::Text => {
                let pasteboard_item = NSPasteboardItem::new();
                let string = NSString::from_str(&item.content);
                if !pasteboard_item.setString_forType(&string, string_type) {
                    return Err(AppError::ClipboardUnavailable);
                }
                if let Some(html) = html {
                    pasteboard_item.setData_forType(&NSData::with_bytes(html), html_type);
                }
                if let Some(rtf) = rtf {
                    pasteboard_item.setData_forType(&NSData::with_bytes(rtf), rtf_type);
                }
                objects.push(ProtocolObject::<dyn NSPasteboardWriting>::from_retained(
                    pasteboard_item,
                ));
                hash_bytes(b"text\0", item.content.as_bytes())
            }
            ClipboardKind::Image => {
                let Some(image_png) = image_png else {
                    return Err(AppError::NotFound);
                };
                let pasteboard_item = NSPasteboardItem::new();
                if !pasteboard_item.setData_forType(&NSData::with_bytes(image_png), png_type) {
                    return Err(AppError::ClipboardUnavailable);
                }
                objects.push(ProtocolObject::<dyn NSPasteboardWriting>::from_retained(
                    pasteboard_item,
                ));
                hash_bytes(b"image\0", image_png)
            }
            ClipboardKind::Files => {
                if item.files.iter().any(|file| !Path::new(file).exists()) {
                    return Err(AppError::FileMissing);
                }
                let mut hasher = Sha256::new();
                hasher.update(b"files\0");
                for file in &item.files {
                    hasher.update(file.as_bytes());
                    hasher.update(b"\0");
                    let url = NSURL::fileURLWithPath(&NSString::from_str(file));
                    let Some(value) = url.absoluteString() else {
                        return Err(AppError::ClipboardUnavailable);
                    };
                    let pasteboard_item = NSPasteboardItem::new();
                    if !pasteboard_item.setString_forType(&value, file_url_type) {
                        return Err(AppError::ClipboardUnavailable);
                    }
                    objects.push(ProtocolObject::<dyn NSPasteboardWriting>::from_retained(
                        pasteboard_item,
                    ));
                }
                hex::encode(hasher.finalize())
            }
        };
        let array = NSArray::from_retained_slice(&objects);
        if !pasteboard.writeObjects(&array) {
            return Err(AppError::ClipboardUnavailable);
        }
        Ok(WriteReceipt {
            change_count: pasteboard.changeCount() as i64,
            content_hash: hash,
        })
    })
}

fn text_title(value: &str) -> String {
    let compact = value
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty())
        .unwrap_or("空白文本");
    let mut title: String = compact.chars().take(72).collect();
    if compact.chars().count() > 72 {
        title.push('…');
    }
    title
}

fn file_title(files: &[String]) -> String {
    let first = Path::new(&files[0])
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("文件");
    if files.len() == 1 {
        first.to_owned()
    } else {
        format!("{} 等 {} 个文件", first, files.len())
    }
}

fn hash_bytes(prefix: &[u8], bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(prefix);
    hasher.update(bytes);
    hex::encode(hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn titles_are_bounded_and_readable() {
        assert_eq!(text_title("\n  hello world\nnext"), "hello world");
        let long = "好".repeat(90);
        assert_eq!(text_title(&long).chars().count(), 73);
        assert_eq!(
            file_title(&["/tmp/one.txt".into(), "/tmp/two.txt".into()]),
            "one.txt 等 2 个文件"
        );
    }

    #[test]
    #[ignore = "covered by the main-thread pasteboard_integration binary"]
    fn named_pasteboard_round_trips_text_image_and_ordered_files() {
        autoreleasepool(|_| {
            let pasteboard_name =
                NSString::from_str(&format!("com.easyclipboard.tests.{}", uuid::Uuid::new_v4()));
            let pasteboard = NSPasteboard::pasteboardWithName(&pasteboard_name);
            let string_type = unsafe { NSPasteboardTypeString };
            let png_type = unsafe { NSPasteboardTypePNG };
            let file_url_type = unsafe { NSPasteboardTypeFileURL };

            let text_item = NSPasteboardItem::new();
            assert!(text_item.setString_forType(&NSString::from_str("hello"), string_type));
            let image_item = NSPasteboardItem::new();
            let mut image_writer = std::io::Cursor::new(Vec::new());
            image::DynamicImage::new_rgba8(2, 2)
                .write_to(&mut image_writer, ImageFormat::Png)
                .unwrap();
            let png = image_writer.into_inner();
            assert!(image_item.setData_forType(&NSData::with_bytes(&png), png_type));
            let first_file = NSPasteboardItem::new();
            let second_file = NSPasteboardItem::new();
            assert!(first_file
                .setString_forType(&NSString::from_str("file:///tmp/one.txt"), file_url_type,));
            assert!(second_file
                .setString_forType(&NSString::from_str("file:///tmp/two.txt"), file_url_type,));
            let objects = vec![
                ProtocolObject::<dyn NSPasteboardWriting>::from_retained(text_item),
                ProtocolObject::<dyn NSPasteboardWriting>::from_retained(image_item),
                ProtocolObject::<dyn NSPasteboardWriting>::from_retained(first_file),
                ProtocolObject::<dyn NSPasteboardWriting>::from_retained(second_file),
            ];
            assert!(pasteboard.writeObjects(&NSArray::from_retained_slice(&objects)));
            let items = pasteboard.pasteboardItems().unwrap();
            assert_eq!(
                items
                    .iter()
                    .next()
                    .unwrap()
                    .stringForType(string_type)
                    .unwrap()
                    .to_string(),
                "hello"
            );
            assert_eq!(
                items
                    .iter()
                    .nth(1)
                    .unwrap()
                    .dataForType(png_type)
                    .unwrap()
                    .to_vec(),
                png
            );
            let files: Vec<String> = items
                .iter()
                .filter_map(|item| item.stringForType(file_url_type))
                .map(|value| value.to_string())
                .collect();
            assert_eq!(files, ["file:///tmp/one.txt", "file:///tmp/two.txt"]);
            pasteboard.clearContents();
        });
    }
}
