use std::path::Path;

use objc2::{rc::autoreleasepool, runtime::ProtocolObject};
use objc2_app_kit::{
    NSPasteboard, NSPasteboardItem, NSPasteboardTypeFileURL, NSPasteboardTypeHTML,
    NSPasteboardTypePNG, NSPasteboardTypeRTF, NSPasteboardTypeString, NSPasteboardTypeTIFF,
    NSPasteboardWriting,
};
use objc2_foundation::{NSArray, NSData, NSString, NSURL};
use tauri::AppHandle;

use crate::{
    domain::clipboard::{
        file_title, hash_bytes, hash_files, normalize_image, normalize_single_image_file,
        text_title, WriteReceipt, FILE_LIMIT, TEXT_LIMIT,
    },
    error::AppError,
    models::{CapturedClipboard, ClipboardItemDetail, ClipboardKind},
    platform::TargetApplication,
};

const SENSITIVE_TYPES: [&str; 3] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

pub fn change_token() -> i64 {
    autoreleasepool(|_| NSPasteboard::generalPasteboard().changeCount() as i64)
}

pub fn read_capture(source: TargetApplication) -> Result<Option<CapturedClipboard>, AppError> {
    autoreleasepool(|_| {
        let pasteboard = NSPasteboard::generalPasteboard();
        let file_url_type = unsafe { NSPasteboardTypeFileURL };
        let png_type = unsafe { NSPasteboardTypePNG };
        let tiff_type = unsafe { NSPasteboardTypeTIFF };
        let jpeg_type = NSString::from_str("public.jpeg");
        let string_type = unsafe { NSPasteboardTypeString };
        let html_type = unsafe { NSPasteboardTypeHTML };
        let rtf_type = unsafe { NSPasteboardTypeRTF };
        let Some(items) = pasteboard.pasteboardItems() else {
            return Ok(None);
        };

        for item in items.iter() {
            for data_type in item.types().iter() {
                if SENSITIVE_TYPES.contains(&data_type.to_string().as_str()) {
                    return Ok(None);
                }
            }
        }

        let files: Vec<String> = items
            .iter()
            .filter_map(|item| item.stringForType(file_url_type))
            .filter_map(|value| NSURL::URLWithString(&value))
            .filter_map(|url| url.path())
            .map(|path| path.to_string())
            .collect();
        let image_bytes = pasteboard
            .dataForType(png_type)
            .or_else(|| pasteboard.dataForType(&jpeg_type))
            .or_else(|| pasteboard.dataForType(tiff_type))
            .map(|value| value.to_vec());

        if !files.is_empty() {
            if files.len() > FILE_LIMIT {
                return Err(AppError::ContentTooLarge);
            }
            if files.len() == 1 {
                let normalized = image_bytes
                    .as_deref()
                    .and_then(|bytes| normalize_image(bytes).ok())
                    .or_else(|| normalize_single_image_file(&files));
                if let Some((png, width, height)) = normalized {
                    let hash = hash_bytes(b"image\0", &png);
                    let byte_size = png.len() as u64;
                    return Ok(Some(CapturedClipboard {
                        kind: ClipboardKind::Image,
                        title: format!("{} · {width} × {height}", file_title(&files)),
                        content: String::new(),
                        html: None,
                        rtf: None,
                        image_png: Some(png),
                        hash,
                        files,
                        source_name: source.name,
                        source_app_id: source.identifier,
                        byte_size,
                    }));
                }
            }
            let byte_size = files
                .iter()
                .filter_map(|file| std::fs::metadata(file).ok())
                .map(|metadata| metadata.len())
                .sum();
            return Ok(Some(CapturedClipboard {
                kind: ClipboardKind::Files,
                title: file_title(&files),
                content: String::new(),
                html: None,
                rtf: None,
                image_png: None,
                hash: hash_files(&files),
                files,
                source_name: source.name,
                source_app_id: source.identifier,
                byte_size,
            }));
        }

        if let Some(data) = image_bytes {
            let (png, width, height) = normalize_image(&data)?;
            let hash = hash_bytes(b"image\0", &png);
            let byte_size = png.len() as u64;
            return Ok(Some(CapturedClipboard {
                kind: ClipboardKind::Image,
                title: format!("图片 · {width} × {height}"),
                content: String::new(),
                html: None,
                rtf: None,
                image_png: Some(png),
                files: vec![],
                source_name: source.name,
                source_app_id: source.identifier,
                byte_size,
                hash,
            }));
        }

        let Some(text) = pasteboard.stringForType(string_type) else {
            return Ok(None);
        };
        let text = text.to_string();
        if text.len() > TEXT_LIMIT {
            return Err(AppError::ContentTooLarge);
        }
        Ok(Some(CapturedClipboard {
            kind: ClipboardKind::Text,
            title: text_title(&text),
            content: text.clone(),
            html: pasteboard
                .dataForType(html_type)
                .map(|value| value.to_vec()),
            rtf: pasteboard.dataForType(rtf_type).map(|value| value.to_vec()),
            image_png: None,
            files: vec![],
            source_name: source.name,
            source_app_id: source.identifier,
            byte_size: text.len() as u64,
            hash: hash_bytes(b"text\0", text.as_bytes()),
        }))
    })
}

pub fn write_item(
    _app: &AppHandle,
    item: &ClipboardItemDetail,
    image_png: Option<&[u8]>,
    html: Option<&[u8]>,
    rtf: Option<&[u8]>,
) -> Result<WriteReceipt, AppError> {
    autoreleasepool(|_| {
        let pasteboard = NSPasteboard::generalPasteboard();
        let file_url_type = unsafe { NSPasteboardTypeFileURL };
        let png_type = unsafe { NSPasteboardTypePNG };
        let string_type = unsafe { NSPasteboardTypeString };
        let html_type = unsafe { NSPasteboardTypeHTML };
        let rtf_type = unsafe { NSPasteboardTypeRTF };
        pasteboard.clearContents();
        let mut objects = Vec::new();
        let hash = match item.summary.kind {
            ClipboardKind::Text => {
                let pasteboard_item = NSPasteboardItem::new();
                if !pasteboard_item
                    .setString_forType(&NSString::from_str(&item.content), string_type)
                {
                    return Err(AppError::ClipboardUnavailable);
                }
                if let Some(html) = html {
                    pasteboard_item.setData_forType(&NSData::with_bytes(html), html_type);
                }
                if let Some(rtf) = rtf {
                    pasteboard_item.setData_forType(&NSData::with_bytes(rtf), rtf_type);
                }
                objects.push(ProtocolObject::<dyn NSPasteboardWriting>::from_retained(
                    pasteboard_item,
                ));
                hash_bytes(b"text\0", item.content.as_bytes())
            }
            ClipboardKind::Image => {
                let image_png = image_png.ok_or(AppError::NotFound)?;
                let pasteboard_item = NSPasteboardItem::new();
                if !pasteboard_item.setData_forType(&NSData::with_bytes(image_png), png_type) {
                    return Err(AppError::ClipboardUnavailable);
                }
                if let Some(file) = item.files.iter().find(|file| Path::new(file).exists()) {
                    let url = NSURL::fileURLWithPath(&NSString::from_str(file));
                    if let Some(value) = url.absoluteString() {
                        pasteboard_item.setString_forType(&value, file_url_type);
                    }
                }
                objects.push(ProtocolObject::<dyn NSPasteboardWriting>::from_retained(
                    pasteboard_item,
                ));
                hash_bytes(b"image\0", image_png)
            }
            ClipboardKind::Files => {
                if item.files.iter().any(|file| !Path::new(file).exists()) {
                    return Err(AppError::FileMissing);
                }
                for file in &item.files {
                    let url = NSURL::fileURLWithPath(&NSString::from_str(file));
                    let value = url.absoluteString().ok_or(AppError::ClipboardUnavailable)?;
                    let pasteboard_item = NSPasteboardItem::new();
                    if !pasteboard_item.setString_forType(&value, file_url_type) {
                        return Err(AppError::ClipboardUnavailable);
                    }
                    objects.push(ProtocolObject::<dyn NSPasteboardWriting>::from_retained(
                        pasteboard_item,
                    ));
                }
                hash_files(&item.files)
            }
        };
        if !pasteboard.writeObjects(&NSArray::from_retained_slice(&objects)) {
            return Err(AppError::ClipboardUnavailable);
        }
        Ok(WriteReceipt {
            change_token: pasteboard.changeCount() as i64,
            content_hash: hash,
        })
    })
}
